version: '3.4'
services:
  db:
    image: postgres:9.6
    container_name: postgres-projeto
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=projeto-banco
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
