
library(ggplot2)

li = list ( c("SVM",
              "Naive Bayes",
              "Maximum Entropy",
              "Naive Bayes",
              "SVM",
              "KNN",
              "Linear Regression",
              "LDA",
              "SVM",
              "Naive Bayes",
              "Naive Bayes",
              "SVM",
              "Random Forest",
              "CNN BLSTM-RNN - Softmax",
              "CNN BLSTM-RNN - SVM",
              "Naive Bayes",
              "SVM",
              "Lasso",
              "Decision Trees",
              "KNN",
              "Regression Analysis",
              "Binary Logistic Regression",
              "Bayes Net",
             "Rocchio Classifier",
              "Perceptron classifier",
              "Bagging",
              "MANCOVA",
              "K-means Algorithm",
              "Latent Semantic Analysis",
              "PCA",
              "ANEW",
              "LIWC",
              "Hierarchical Dirichlet process",
              "Emolex",
              "IsaWika lexicon",
              "LDA",
              "Logistic Regression",
              "Decision Trees",
              "SVM",
              "KNN",
              "Decision Trees",
              "Ensemble",
              "RNN",
              "SVM",
              "Naive Bayes",
              "Decision Trees",
              "Lasso",
              "Naive Bayes",
              "SVM",
              "Logistic Regression",
              "Semantic Analysis",
              "Naive Bayes",
              "SVM",
              "Logistic Regression",
              "KNN",
              "IBK",
              "j48",
              "SMO",
              "PART",
              "PLN",
              "SVM",
              "Random Forest",
              "PLN",
              "Lexicos",
              "CNN",
              "Naive Bayes",
              "KNN",
              "PLN",
              "LDA",
              "SVM",
              "LIWC"))

dt = data.frame(li)

dt$c..SVM....Naive.Bayes....Maximum.Entropy....Naive.Bayes....SVM...

View(dt)

ggplot(dt, aes(x = c..SVM....Naive.Bayes....Maximum.Entropy....Naive.Bayes....SVM..., colour = c..SVM....Naive.Bayes....Maximum.Entropy....Naive.Bayes....SVM..., fill = c..SVM....Naive.Bayes....Maximum.Entropy....Naive.Bayes....SVM...)) + geom_bar() + theme_bw()
